### ISSUE TITLE
PluginActivator实现类强转PluginActivator遇到ClassCastException

### ISSUE THREAD

**Issue by shensi199312** [alibaba/one-java-agent#14]
![image](https://user-images.githubusercontent.com/18387126/111093926-0d8dd980-8575-11eb-9344-b587ed81b890.png)
如图，这行代码会抛出ClassCastException.
原因是:PluginActivator这个接口由AppClassLoader加载,activatorClass是由AppClassLoader的子类加载器PlguinClassLoader加载，强转抛出了ClassCastException.
是我的姿势不对吗,导致PluginActivator提前被AppClassLoader加载了吗?

**Comment by hengyunabc** [comment]
应用本身不能依赖`PluginActivator`所在的jar。应用是在启动时，用 `-javaagent`参数引入 agent。

**Comment by shensi199312** [comment]
> 应用本身不能依赖`PluginActivator`所在的jar。应用是在启动时，用 `-javaagent`参数引入 agent。

嗯嗯,问题解决,🙏
