### ISSUE TITLE
tomcat下使用agent无法加载类

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [alibaba/one-java-agent#48]
premain、main默认是appclassloader,但是tomcat加载catalina是urlclassloader，由于是双亲委托机制，父类appclassloader不能访问子类urlclassloader,所以会报错not found
怎么解决

**Comment by feifeiiiiiiiiiii** [comment]
@hengyunabc

**Comment by hengyunabc** [comment]
plugin里要注册 `io.oneagent.service.ClassLoaderHandler` ，把自己的package注册上去。

**Comment by feifeiiiiiiiiiii** [comment]
> plugin里要注册 `io.oneagent.service.ClassLoaderHandler` ，把自己的package注册上去。

谢谢

**Comment by lastboy1228** [comment]
定义了ClassLoaderHandler来指定工具类的包后，spring加载时才用到的类，里面注入的增强代码能够调用到工具类；
catalina加载时就用到的类，如果被增强，无法找到其依赖的工具类
